--[[
    Constantes globais
]]

-- Constantes da janela
VIRTUAL_W = 224
VIRTUAL_H = 256
WINDOW_W = VIRTUAL_W * 2.5
WINDOW_H = VIRTUAL_H * 2.5

-- Constantes de sprites
SPRITE_SIZE = 15

-- Constantes do jogador
PLAYER_START_X = VIRTUAL_W/2 - SPRITE_SIZE
PLAYER_START_Y = VIRTUAL_H - SPRITE_SIZE
PLAYER_MAX_SPEED = 100
PLAYER_ACCELERATION = 500
PLAYER_COOLDOWN = 0.65
PLAYER_SPRITES = {13, 14, 15, 16}
-- Constantes dos inimigos
ALIEN_START_X = VIRTUAL_W/2 - SPRITE_SIZE
ALIEN_START_Y = 30
ALIEN_STEP_LENGTH = 6
ALIEN_STEP_HEIGHT = 12
ALIEN1_SPRITES = {1,2,3,4}
ALIEN2_SPRITES = {5,6,7,8}
ALIEN3_SPRITES = {9,10,11,12}

-- Constantes de projéteis
PROJECTILE_LENGTH = 5
PROJECTILE_SPEED = 300
ALIEN_PROJECTILE_SPEED = 90
